export const Products = [
  {
    id: 3,
    name: 'Black Leather Jacket',
    brand: 'Allen Solly',
    price: 800,
    category: 'Jacket',
    type: 'Sports',
    sizeAvailable: ['S', 'M', 'L', 'XL', '2XL'],
    colorAvailable: [
      'black',
      'green',
      'white',
      'blue'
    ],
    description:
      'A classic staple for colder days, this rich brown woolen jacket combines warmth with refined style. Made from high-quality wool, it provides excellent insulation while maintaining breathability.',
    image: require('../../assets/images/Jacket/Jacket3.jpg'),
  },
  {
    id: 1,
    name: 'Brown Leather Jacket',
    brand: 'Puma',
    price: 600,
    category: 'Jacket',
    type: 'Winter-Wear',
    sizeAvailable: ['S', 'M', '2XL'],
    colorAvailable: ['black', 'violet', 'grey', 'blue', 'brown'],
    description:
      'Crafted from premium genuine leather, this jacket offers a smooth texture, durability, and a perfect fit. Featuring a zippered front, classic lapel collar, and snug cuffs.',
    image: require('../../assets/images/Jacket/Jacket1.jpg'),
  },
  {
    id: 2,
    name: 'White WoolenJacket',
    brand: 'H & M',
    price: 1000,
    category: 'Jacket',
    type: 'Winter-Wear',
    sizeAvailable: ['L', 'XL', '2XL'],
    colorAvailable: ['black', 'green', 'brown'],
    description:
      'The minimalist design, structured fit, and button-up front make it a perfect blend of sophistication and warmth. Whether paired with jeans or a dress, this jacket exudes effortless charm and winter elegance.',
    image: require('../../assets/images/Jacket/Jacket2.jpg'),
  },
  {
    id: 4,
    name: 'Long Jacket',
    brand: 'Allen Solly',
    price: 1600,
    category: 'Jacket',
    type: 'Casual',
    sizeAvailable: ['S', 'M', 'L'],
    colorAvailable: ['black', 'green', 'white', 'silver'],
    description:
      'Stay stylish and cozy with this long jacket, designed for maximum warmth and elegance. Its tailored fit and high-quality material make it a perfect companion for chilly days.',
    image: require('../../assets/images/wishList/long-jacket.jpg'),
  },
  {
    id: 5,
    name: 'Linen Shirt',
    brand: 'Puma',
    price: 900,
    category: 'Shirt',
    type: 'Casual',
    sizeAvailable: ['S', 'XL', '2XL'],
    colorAvailable: ['pink', 'white', 'blue', 'brown'],
    description:
      'Made from breathable and lightweight linen, this shirt is perfect for warm weather. Its relaxed fit and classic button-down style make it a versatile choice for any occasion.',
    image: require('../../assets/images/wishList/shirt.jpg'),
  },
  {
    id: 6,
    name: 'Winter Polo',
    brand: 'H & M',
    price: 1000,
    category: 'T-Shirt',
    type: 'Formal',
    sizeAvailable: ['S', 'M', 'L', '2XL'],
    colorAvailable: ['black', 'green', 'orange', 'brown'],
    description:
      'A refined polo shirt designed for the winter season, featuring soft wool-blend fabric for extra warmth. Its sleek and minimalistic design pairs effortlessly with both casual and formal outfits.',
    image: require('../../assets/images/wishList/polo1.jpg'),
  },
  {
    id: 7,
    name: 'Casual Polo',
    brand: 'Nike',
    price: 800,
    category: 'T-Shirt',
    type: 'Casual',
    sizeAvailable: ['L', 'XL', '2XL'],
    colorAvailable: ['black', 'green'],
    description:
      'A must-have for every wardrobe, this casual polo shirt offers comfort and style in equal measure. Made from premium cotton, it ensures breathability and a relaxed fit for all-day wear.',
    image: require('../../assets/images/wishList/polo2.jpg'),
  },
];
