export const product = [
  {
    id: '1',
    title: '#Casual Shirt',
    brand: 'HIGHLANDER',
    discount: '40%',
    price: '₹899',
    originalPrice: '₹1,499',
    rating: '4.3',
    imageUrl: require("../../assets/images/Product/HighLander_Casual_Shirt.webp"),
  },
  {
    id: '2',
    title: '#Slim Fit Jeans',
    brand: 'LEVI’S',
    discount: '30%',
    price: '₹1,299',
    originalPrice: '₹1,899',
    rating: '4.5',
    imageUrl: require("../../assets/images/Product/Levi_Slim_Fit_Jean.webp"),
  },
  {
    id: '3',
    title: '#Formal Blazer',
    brand: 'PETER ENGLAND',
    discount: '35%',
    price: '₹2,599',
    originalPrice: '₹3,999',
    rating: '4.7',
    imageUrl: require("../../assets/images/Product/Peter_England.webp"),
  },
  {
    id: '4',
    title: '#Polo T-Shirt',
    brand: 'U.S. POLO ASSN.',
    discount: '25%',
    price: '₹749',
    originalPrice: '₹999',
    rating: '4.4',
    imageUrl: require("../../assets/images/Product/US_Polo.webp"),
  },
  {
    id: '5',
    title: '#Leather Jacket',
    brand: 'ZARA',
    discount: '50%',
    price: '₹3,499',
    originalPrice: '₹6,999',
    rating: '4.6',
    imageUrl: require("../../assets/images/Product/Zara.webp"),
  },
  {
    id: '6',
    title: '#Chinos',
    brand: 'H&M',
    discount: '20%',
    price: '₹1,199',
    originalPrice: '₹1,499',
    rating: '4.2',
    imageUrl: require("../../assets/images/Product/HM.jpg"),
  },
  {
    id: '7',
    title: '#Sneakers',
    brand: 'NIKE',
    discount: '30%',
    price: '₹2,799',
    originalPrice: '₹3,999',
    rating: '4.8',
    imageUrl: require("../../assets/images/Product/nike.webp"),
  },
  {
    id: '8',
    title: '#Running Shoes',
    brand: 'ADIDAS',
    discount: '40%',
    price: '₹2,499',
    originalPrice: '₹4,199',
    rating: '4.5',
    imageUrl:require("../../assets/images/Product/adidas.webp"),
  },
  {
    id: '9',
    title: '#Hoodie',
    brand: 'PUMA',
    discount: '30%',
    price: '₹1,399',
    originalPrice: '₹1,999',
    rating: '4.3',
    imageUrl:require("../../assets/images/Product/puma.webp"),
  },
  {
    id: '10',
    title: '#Graphic T-Shirt',
    brand: 'ROADSTER',
    discount: '45%',
    price: '₹549',
    originalPrice: '₹999',
    rating: '4.2',
    imageUrl: require("../../assets/images/Product/roadster.webp"),
  },
];
